### ISSUE TITLE
Car Evolution dataset

### ISSUE THREAD

**Issue by ZichenMiao** [mancinimassimiliano/adagraph#4]
Could you please share a copy of the car evolution dataset? I could not download it from the original web. Thanks.

**Comment by mancinimassimiliano** [comment]
Hi @ZichenMiao and sorry for the late reply.

I am sorry that the dataset is not available anymore from the official website. At the same time, I did not collect the dataset, thus I am not sure whether I have the rights to share it. I suggest that you redirect the request directly to the authors who originally collected it.
